### ISSUE TITLE
How to change port?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [dmac/spin#10]
I couldn't find any information on how to change the port the app is running on. Not even by searching for `8000` or `port` in the source code files here on Github. Is there a way to do this?

**Comment by jboynyc** [comment]
You can `(run #:port 7070)`. These parameters are passed to the web servlet for which spin just provides a wrapper. 

See the full list of options you can pass to `run` [here](https://docs.racket-lang.org/web-server/run.html#%28part._.Full_.A.P.I%29).

**Comment by ZelphirKaltstahl** [comment]
@jboynyc I see. I think this can be closed then :+1:
